#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcmeApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AcmeDB")]
	public partial class AcmeDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdNewspaper(AdNewspaper instance);
    partial void UpdateAdNewspaper(AdNewspaper instance);
    partial void DeleteAdNewspaper(AdNewspaper instance);
    partial void InsertNewsPaper(NewsPaper instance);
    partial void UpdateNewsPaper(NewsPaper instance);
    partial void DeleteNewsPaper(NewsPaper instance);
    partial void InsertAdvertisement(Advertisement instance);
    partial void UpdateAdvertisement(Advertisement instance);
    partial void DeleteAdvertisement(Advertisement instance);
    #endregion
		
		public AcmeDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AcmeDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AcmeDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AcmeDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AcmeDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AcmeDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AdNewspaper> AdNewspapers
		{
			get
			{
				return this.GetTable<AdNewspaper>();
			}
		}
		
		public System.Data.Linq.Table<NewsPaper> NewsPapers
		{
			get
			{
				return this.GetTable<NewsPaper>();
			}
		}
		
		public System.Data.Linq.Table<Advertisement> Advertisements
		{
			get
			{
				return this.GetTable<Advertisement>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdNewspaperDeleteRow")]
		public int AdNewspaperDeleteRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RelationId", DbType="Int")] System.Nullable<int> relationId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), relationId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdNewspaperInsertRow")]
		public int AdNewspaperInsertRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdId", DbType="Int")] System.Nullable<int> adId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaperId", DbType="Int")] System.Nullable<int> paperId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adId, paperId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdNewspaperSelectAll")]
		public ISingleResult<AdNewspaperSelectAllResult> AdNewspaperSelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<AdNewspaperSelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdNewspaperSelectRow")]
		public ISingleResult<AdNewspaperSelectRowResult> AdNewspaperSelectRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RelationId", DbType="Int")] System.Nullable<int> relationId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), relationId);
			return ((ISingleResult<AdNewspaperSelectRowResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdNewspaperUpdateRow")]
		public int AdNewspaperUpdateRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RelationId", DbType="Int")] System.Nullable<int> relationId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdId", DbType="Int")] System.Nullable<int> adId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaperId", DbType="Int")] System.Nullable<int> paperId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), relationId, adId, paperId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdvertisementDeleteRow")]
		public int AdvertisementDeleteRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdvertisementInsertRow")]
		public int AdvertisementInsertRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdName", DbType="NVarChar(50)")] string adName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Text", DbType="NVarChar(MAX)")] string text, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublishDate", DbType="DateTime")] System.Nullable<System.DateTime> publishDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddDate", DbType="Date")] System.Nullable<System.DateTime> addDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adName, text, publishDate, addDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdvertisementSelectAll")]
		public ISingleResult<AdvertisementSelectAllResult> AdvertisementSelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<AdvertisementSelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdvertisementSelectRow")]
		public ISingleResult<AdvertisementSelectRowResult> AdvertisementSelectRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<AdvertisementSelectRowResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdvertisementUpdateRow")]
		public int AdvertisementUpdateRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdName", DbType="NVarChar(50)")] string adName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Text", DbType="NVarChar(MAX)")] string text, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublishDate", DbType="DateTime")] System.Nullable<System.DateTime> publishDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddDate", DbType="Date")] System.Nullable<System.DateTime> addDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, adName, text, publishDate, addDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NewsPaperDeleteRow")]
		public int NewsPaperDeleteRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaperId", DbType="Int")] System.Nullable<int> paperId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paperId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NewsPaperInsertRow")]
		public int NewsPaperInsertRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddDate", DbType="DateTime")] System.Nullable<System.DateTime> addDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, addDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NewsPaperSelectAll")]
		public ISingleResult<NewsPaperSelectAllResult> NewsPaperSelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<NewsPaperSelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NewsPaperSelectRow")]
		public ISingleResult<NewsPaperSelectRowResult> NewsPaperSelectRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaperId", DbType="Int")] System.Nullable<int> paperId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paperId);
			return ((ISingleResult<NewsPaperSelectRowResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NewsPaperUpdateRow")]
		public int NewsPaperUpdateRow([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaperId", DbType="Int")] System.Nullable<int> paperId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddDate", DbType="DateTime")] System.Nullable<System.DateTime> addDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paperId, name, addDate);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdNewspaper")]
	public partial class AdNewspaper : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RelationId;
		
		private int _AdId;
		
		private int _PaperId;
		
		private EntityRef<NewsPaper> _NewsPaper;
		
		private EntityRef<Advertisement> _Advertisement;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRelationIdChanging(int value);
    partial void OnRelationIdChanged();
    partial void OnAdIdChanging(int value);
    partial void OnAdIdChanged();
    partial void OnPaperIdChanging(int value);
    partial void OnPaperIdChanged();
    #endregion
		
		public AdNewspaper()
		{
			this._NewsPaper = default(EntityRef<NewsPaper>);
			this._Advertisement = default(EntityRef<Advertisement>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RelationId
		{
			get
			{
				return this._RelationId;
			}
			set
			{
				if ((this._RelationId != value))
				{
					this.OnRelationIdChanging(value);
					this.SendPropertyChanging();
					this._RelationId = value;
					this.SendPropertyChanged("RelationId");
					this.OnRelationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdId", DbType="Int NOT NULL")]
		public int AdId
		{
			get
			{
				return this._AdId;
			}
			set
			{
				if ((this._AdId != value))
				{
					if (this._Advertisement.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdIdChanging(value);
					this.SendPropertyChanging();
					this._AdId = value;
					this.SendPropertyChanged("AdId");
					this.OnAdIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaperId", DbType="Int NOT NULL")]
		public int PaperId
		{
			get
			{
				return this._PaperId;
			}
			set
			{
				if ((this._PaperId != value))
				{
					if (this._NewsPaper.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPaperIdChanging(value);
					this.SendPropertyChanging();
					this._PaperId = value;
					this.SendPropertyChanged("PaperId");
					this.OnPaperIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewsPaper_AdNewspaper", Storage="_NewsPaper", ThisKey="PaperId", OtherKey="PaperId", IsForeignKey=true)]
		public NewsPaper NewsPaper
		{
			get
			{
				return this._NewsPaper.Entity;
			}
			set
			{
				NewsPaper previousValue = this._NewsPaper.Entity;
				if (((previousValue != value) 
							|| (this._NewsPaper.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NewsPaper.Entity = null;
						previousValue.AdNewspapers.Remove(this);
					}
					this._NewsPaper.Entity = value;
					if ((value != null))
					{
						value.AdNewspapers.Add(this);
						this._PaperId = value.PaperId;
					}
					else
					{
						this._PaperId = default(int);
					}
					this.SendPropertyChanged("NewsPaper");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Advertisement_AdNewspaper", Storage="_Advertisement", ThisKey="AdId", OtherKey="ID", IsForeignKey=true)]
		public Advertisement Advertisement
		{
			get
			{
				return this._Advertisement.Entity;
			}
			set
			{
				Advertisement previousValue = this._Advertisement.Entity;
				if (((previousValue != value) 
							|| (this._Advertisement.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Advertisement.Entity = null;
						previousValue.AdNewspapers.Remove(this);
					}
					this._Advertisement.Entity = value;
					if ((value != null))
					{
						value.AdNewspapers.Add(this);
						this._AdId = value.ID;
					}
					else
					{
						this._AdId = default(int);
					}
					this.SendPropertyChanged("Advertisement");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewsPaper")]
	public partial class NewsPaper : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PaperId;
		
		private string _Name;
		
		private System.DateTime _AddDate;
		
		private EntitySet<AdNewspaper> _AdNewspapers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPaperIdChanging(int value);
    partial void OnPaperIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddDateChanging(System.DateTime value);
    partial void OnAddDateChanged();
    #endregion
		
		public NewsPaper()
		{
			this._AdNewspapers = new EntitySet<AdNewspaper>(new Action<AdNewspaper>(this.attach_AdNewspapers), new Action<AdNewspaper>(this.detach_AdNewspapers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaperId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PaperId
		{
			get
			{
				return this._PaperId;
			}
			set
			{
				if ((this._PaperId != value))
				{
					this.OnPaperIdChanging(value);
					this.SendPropertyChanging();
					this._PaperId = value;
					this.SendPropertyChanged("PaperId");
					this.OnPaperIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddDate", DbType="DateTime NOT NULL")]
		public System.DateTime AddDate
		{
			get
			{
				return this._AddDate;
			}
			set
			{
				if ((this._AddDate != value))
				{
					this.OnAddDateChanging(value);
					this.SendPropertyChanging();
					this._AddDate = value;
					this.SendPropertyChanged("AddDate");
					this.OnAddDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NewsPaper_AdNewspaper", Storage="_AdNewspapers", ThisKey="PaperId", OtherKey="PaperId")]
		public EntitySet<AdNewspaper> AdNewspapers
		{
			get
			{
				return this._AdNewspapers;
			}
			set
			{
				this._AdNewspapers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AdNewspapers(AdNewspaper entity)
		{
			this.SendPropertyChanging();
			entity.NewsPaper = this;
		}
		
		private void detach_AdNewspapers(AdNewspaper entity)
		{
			this.SendPropertyChanging();
			entity.NewsPaper = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Advertisement")]
	public partial class Advertisement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _AdName;
		
		private string _Text;
		
		private System.DateTime _PublishDate;
		
		private System.DateTime _AddDate;
		
		private EntitySet<AdNewspaper> _AdNewspapers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAdNameChanging(string value);
    partial void OnAdNameChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnPublishDateChanging(System.DateTime value);
    partial void OnPublishDateChanged();
    partial void OnAddDateChanging(System.DateTime value);
    partial void OnAddDateChanged();
    #endregion
		
		public Advertisement()
		{
			this._AdNewspapers = new EntitySet<AdNewspaper>(new Action<AdNewspaper>(this.attach_AdNewspapers), new Action<AdNewspaper>(this.detach_AdNewspapers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AdName
		{
			get
			{
				return this._AdName;
			}
			set
			{
				if ((this._AdName != value))
				{
					this.OnAdNameChanging(value);
					this.SendPropertyChanging();
					this._AdName = value;
					this.SendPropertyChanged("AdName");
					this.OnAdNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime NOT NULL")]
		public System.DateTime PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this.OnPublishDateChanging(value);
					this.SendPropertyChanging();
					this._PublishDate = value;
					this.SendPropertyChanged("PublishDate");
					this.OnPublishDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddDate", DbType="Date NOT NULL")]
		public System.DateTime AddDate
		{
			get
			{
				return this._AddDate;
			}
			set
			{
				if ((this._AddDate != value))
				{
					this.OnAddDateChanging(value);
					this.SendPropertyChanging();
					this._AddDate = value;
					this.SendPropertyChanged("AddDate");
					this.OnAddDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Advertisement_AdNewspaper", Storage="_AdNewspapers", ThisKey="ID", OtherKey="AdId")]
		public EntitySet<AdNewspaper> AdNewspapers
		{
			get
			{
				return this._AdNewspapers;
			}
			set
			{
				this._AdNewspapers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AdNewspapers(AdNewspaper entity)
		{
			this.SendPropertyChanging();
			entity.Advertisement = this;
		}
		
		private void detach_AdNewspapers(AdNewspaper entity)
		{
			this.SendPropertyChanging();
			entity.Advertisement = null;
		}
	}
	
	public partial class AdNewspaperSelectAllResult
	{
		
		private int _RelationId;
		
		private int _AdId;
		
		private int _PaperId;
		
		public AdNewspaperSelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationId", DbType="Int NOT NULL")]
		public int RelationId
		{
			get
			{
				return this._RelationId;
			}
			set
			{
				if ((this._RelationId != value))
				{
					this._RelationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdId", DbType="Int NOT NULL")]
		public int AdId
		{
			get
			{
				return this._AdId;
			}
			set
			{
				if ((this._AdId != value))
				{
					this._AdId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaperId", DbType="Int NOT NULL")]
		public int PaperId
		{
			get
			{
				return this._PaperId;
			}
			set
			{
				if ((this._PaperId != value))
				{
					this._PaperId = value;
				}
			}
		}
	}
	
	public partial class AdNewspaperSelectRowResult
	{
		
		private int _RelationId;
		
		private int _AdId;
		
		private int _PaperId;
		
		public AdNewspaperSelectRowResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationId", DbType="Int NOT NULL")]
		public int RelationId
		{
			get
			{
				return this._RelationId;
			}
			set
			{
				if ((this._RelationId != value))
				{
					this._RelationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdId", DbType="Int NOT NULL")]
		public int AdId
		{
			get
			{
				return this._AdId;
			}
			set
			{
				if ((this._AdId != value))
				{
					this._AdId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaperId", DbType="Int NOT NULL")]
		public int PaperId
		{
			get
			{
				return this._PaperId;
			}
			set
			{
				if ((this._PaperId != value))
				{
					this._PaperId = value;
				}
			}
		}
	}
	
	public partial class AdvertisementSelectAllResult
	{
		
		private int _ID;
		
		private string _AdName;
		
		private string _Text;
		
		private System.DateTime _PublishDate;
		
		private System.DateTime _AddDate;
		
		public AdvertisementSelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AdName
		{
			get
			{
				return this._AdName;
			}
			set
			{
				if ((this._AdName != value))
				{
					this._AdName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime NOT NULL")]
		public System.DateTime PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this._PublishDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddDate", DbType="Date NOT NULL")]
		public System.DateTime AddDate
		{
			get
			{
				return this._AddDate;
			}
			set
			{
				if ((this._AddDate != value))
				{
					this._AddDate = value;
				}
			}
		}
	}
	
	public partial class AdvertisementSelectRowResult
	{
		
		private int _ID;
		
		private string _AdName;
		
		private string _Text;
		
		private System.DateTime _PublishDate;
		
		private System.DateTime _AddDate;
		
		public AdvertisementSelectRowResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AdName
		{
			get
			{
				return this._AdName;
			}
			set
			{
				if ((this._AdName != value))
				{
					this._AdName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime NOT NULL")]
		public System.DateTime PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this._PublishDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddDate", DbType="Date NOT NULL")]
		public System.DateTime AddDate
		{
			get
			{
				return this._AddDate;
			}
			set
			{
				if ((this._AddDate != value))
				{
					this._AddDate = value;
				}
			}
		}
	}
	
	public partial class NewsPaperSelectAllResult
	{
		
		private int _PaperId;
		
		private string _Name;
		
		private System.DateTime _AddDate;
		
		public NewsPaperSelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaperId", DbType="Int NOT NULL")]
		public int PaperId
		{
			get
			{
				return this._PaperId;
			}
			set
			{
				if ((this._PaperId != value))
				{
					this._PaperId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddDate", DbType="DateTime NOT NULL")]
		public System.DateTime AddDate
		{
			get
			{
				return this._AddDate;
			}
			set
			{
				if ((this._AddDate != value))
				{
					this._AddDate = value;
				}
			}
		}
	}
	
	public partial class NewsPaperSelectRowResult
	{
		
		private int _PaperId;
		
		private string _Name;
		
		private System.DateTime _AddDate;
		
		public NewsPaperSelectRowResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaperId", DbType="Int NOT NULL")]
		public int PaperId
		{
			get
			{
				return this._PaperId;
			}
			set
			{
				if ((this._PaperId != value))
				{
					this._PaperId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddDate", DbType="DateTime NOT NULL")]
		public System.DateTime AddDate
		{
			get
			{
				return this._AddDate;
			}
			set
			{
				if ((this._AddDate != value))
				{
					this._AddDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
