<?xml version="1.0" encoding="utf-8"?><Database Name="AcmeDB" Class="AcmeDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\AcmeDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AcmeDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AdNewspaper" Member="AdNewspapers">
    <Type Name="AdNewspaper">
      <Column Name="RelationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaperId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="NewsPaper_AdNewspaper" Member="NewsPaper" ThisKey="PaperId" OtherKey="PaperId" Type="NewsPaper" IsForeignKey="true" />
      <Association Name="Advertisement_AdNewspaper" Member="Advertisement" ThisKey="AdId" OtherKey="ID" Type="Advertisement" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewsPaper" Member="NewsPapers">
    <Type Name="NewsPaper">
      <Column Name="PaperId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="NewsPaper_AdNewspaper" Member="AdNewspapers" ThisKey="PaperId" OtherKey="PaperId" Type="AdNewspaper" />
    </Type>
  </Table>
  <Table Name="dbo.Advertisement" Member="Advertisements">
    <Type Name="Advertisement">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AddDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Advertisement_AdNewspaper" Member="AdNewspapers" ThisKey="ID" OtherKey="AdId" Type="AdNewspaper" />
    </Type>
  </Table>
  <Function Name="dbo.AdNewspaperDeleteRow" Method="AdNewspaperDeleteRow">
    <Parameter Name="RelationId" Parameter="relationId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AdNewspaperInsertRow" Method="AdNewspaperInsertRow">
    <Parameter Name="AdId" Parameter="adId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PaperId" Parameter="paperId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AdNewspaperSelectAll" Method="AdNewspaperSelectAll">
    <ElementType Name="AdNewspaperSelectAllResult">
      <Column Name="RelationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaperId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AdNewspaperSelectRow" Method="AdNewspaperSelectRow">
    <Parameter Name="RelationId" Parameter="relationId" Type="System.Int32" DbType="Int" />
    <ElementType Name="AdNewspaperSelectRowResult">
      <Column Name="RelationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaperId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AdNewspaperUpdateRow" Method="AdNewspaperUpdateRow">
    <Parameter Name="RelationId" Parameter="relationId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdId" Parameter="adId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PaperId" Parameter="paperId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AdvertisementDeleteRow" Method="AdvertisementDeleteRow">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AdvertisementInsertRow" Method="AdvertisementInsertRow">
    <Parameter Name="AdName" Parameter="adName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Text" Parameter="text" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="PublishDate" Parameter="publishDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="AddDate" Parameter="addDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AdvertisementSelectAll" Method="AdvertisementSelectAll">
    <ElementType Name="AdvertisementSelectAllResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AddDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AdvertisementSelectRow" Method="AdvertisementSelectRow">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="AdvertisementSelectRowResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AddDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AdvertisementUpdateRow" Method="AdvertisementUpdateRow">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdName" Parameter="adName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Text" Parameter="text" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="PublishDate" Parameter="publishDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="AddDate" Parameter="addDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NewsPaperDeleteRow" Method="NewsPaperDeleteRow">
    <Parameter Name="PaperId" Parameter="paperId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NewsPaperInsertRow" Method="NewsPaperInsertRow">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="AddDate" Parameter="addDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NewsPaperSelectAll" Method="NewsPaperSelectAll">
    <ElementType Name="NewsPaperSelectAllResult">
      <Column Name="PaperId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.NewsPaperSelectRow" Method="NewsPaperSelectRow">
    <Parameter Name="PaperId" Parameter="paperId" Type="System.Int32" DbType="Int" />
    <ElementType Name="NewsPaperSelectRowResult">
      <Column Name="PaperId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.NewsPaperUpdateRow" Method="NewsPaperUpdateRow">
    <Parameter Name="PaperId" Parameter="paperId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="AddDate" Parameter="addDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
</Database>